# Generated by Django 4.1.2 on 2022-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.TextField(max_length=6000, default='', editable=False),
        ),
    ]
